"""Bayesian label-prior adaptation from unlabeled test data (label shift)."""

from .mcmc import (
    MCMCResult,
    posterior_label_probabilities,
    sample_prior_posterior,
)
from .predictors import (
    bayes_decision,
    confusion_matrix,
    corrected_posterior,
    format_confusion,
    format_per_class_error,
    per_class_error,
    zero_one_loss_matrix,
)
from .reject_option import (
    AURC50_CAVEAT,
    AURC50_NOTE,
    MIN_COVERAGE,
    REJECT_COLORS,
    REJECT_LABELS,
    Aggregation,
    accuracy,
    bayesian_posterior_and_aleatoric,
    coverage_at_target,
    epistemic_metrics,
    generalize_curve,
    selective_curves,
    sweep_avg_row,
    sweep_epi_avg_row,
    truncated_area,
)

__all__ = [
    "MCMCResult",
    "sample_prior_posterior",
    "posterior_label_probabilities",
    "bayes_decision",
    "corrected_posterior",
    "confusion_matrix",
    "format_confusion",
    "per_class_error",
    "format_per_class_error",
    "zero_one_loss_matrix",
    "AURC50_CAVEAT",
    "AURC50_NOTE",
    "MIN_COVERAGE",
    "REJECT_COLORS",
    "REJECT_LABELS",
    "Aggregation",
    "accuracy",
    "bayesian_posterior_and_aleatoric",
    "coverage_at_target",
    "epistemic_metrics",
    "generalize_curve",
    "selective_curves",
    "sweep_avg_row",
    "sweep_epi_avg_row",
    "truncated_area",
]
